language: node_js
node_js:
  - 6
  - node
env:
  - NODE_ENV=production
sudo: false
cache:
  directories:
    - node_modules
install:
  - npm --production=false install
  - npm --production=false update
  - npm --production=false prune
jobs:
  include:
    - stage: test
      script:
      - npm run test:lint
      - npm run test:unit -- --jobs=4
      - npm run test:integration -- --jobs=4
    - stage: build
      script: npm run build
      skip_cleanup: true
      node_js: 6
      before_deploy:
      - npm --no-git-tag-version version $($(npm bin)/json -f package.json version)-prerelease.$(date +%s)
      - git config --global user.email $(git log --pretty=format:"%ae" -n1)
      - git config --global user.name $(git log --pretty=format:"%an" -n1)
      deploy:
        on:
          all_branches: true
          condition: $RELEASE_BRANCHES =~ $TRAVIS_BRANCH
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
