version: 2.1

orbs:
  commitlint: conventional-changelog/commitlint@1.0.0
  node: circleci/node@5.1.0

executors:
  default-executor:
    docker:
      - image: "cimg/node:16.20.0-browsers"
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  setup:
    steps:
      - checkout
      - node/install-packages

workflows:
  commitlint:
    jobs:
      - commitlint/lint:
          target-branch: develop
          filters:
            branches:
              ignore:
                - develop
                - main
  build-test:
    jobs:
      - build_test

jobs:
  build_test:
    executor: default-executor
    steps:
      - setup
