name: Install system library dependencies
description: Detect missing system library dependencies and install any that are missing.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Using pkg-config $(pkg-config --version)"
        # These dependencies are from scratch-paint -> paper.js -> canvas
        # See also `util/has_lib.js` in the `canvas` package
        # There must be a better way to detect gif_lib.h than this...
        missing_libraries="$(
          ldconfig -p | grep -q 'libcairo\.so' || echo libcairo2-dev
          pkg-config pangocairo || echo libpango1.0-dev
          pkg-config libssl || echo libssl-dev
          pkg-config libjpeg || echo libjpeg-dev
          test -f /usr/include/gif_lib.h || echo libgif-dev
        )"
        echo "Missing libraries: [$missing_libraries]"
        if [ -n "$missing_libraries" ]; then
          sudo apt update # avoiding this is the main reason for detecting missing libraries
          sudo apt install -y $missing_libraries
        else
          echo "No missing libraries"
        fi
