name: CI/CD
on:
  push:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest
    steps:
      - run: echo "Placeholder"
