name: CI

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci:
    name: Detect affected packages, build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - uses: wagoid/commitlint-github-action@v5
      - name: Debug info
        run: |
          cat <<EOF
          Scratch environment: ${{ vars.SCRATCH_ENV || '<none>' }}
          Node version: $(node --version)
          NPM version: $(npm --version)
          GitHub ref: ${{ github.ref }}
          GitHub head ref: ${{ github.head_ref }}
          Working directory: $(pwd)
          EOF

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            any-workspace:
              - ".github/workflows/ci.yml"
              - "packages/**"
            scratch-svg-renderer:
              - ".github/workflows/ci.yml"
              - "packages/scratch-svg-renderer/**"
            scratch-render:
              - ".github/workflows/ci.yml"
              - "packages/scratch-render/**"
              - "packages/scratch-svg-renderer/**"
            scratch-vm:
              - ".github/workflows/ci.yml"
              - "packages/scratch-render/**"
              - "packages/scratch-svg-renderer/**"
              - "packages/scratch-vm/**"
            scratch-gui:
              - ".github/workflows/ci.yml"
              - "packages/scratch-gui/**"
              - "packages/scratch-render/**"
              - "packages/scratch-svg-renderer/**"
              - "packages/scratch-vm/**"

      - if: ${{ steps.filter.outputs.any-workspace == 'true' }}
        uses: ./.github/actions/install-dependencies

      - name: Build packages
        if: ${{ steps.filter.outputs.any-workspace == 'true' }}
        run: npm run build

      - name: Test scratch-svg-renderer
        if: ${{ !cancelled() && steps.filter.outputs.scratch-svg-renderer == 'true' }}
        uses: ./.github/actions/test-package
        with:
          package_name: scratch-svg-renderer
      - name: Test scratch-render
        if: ${{ !cancelled() && steps.filter.outputs.scratch-render == 'true' }}
        uses: ./.github/actions/test-package
        with:
          package_name: scratch-render
      - name: Test scratch-vm
        if: ${{ !cancelled() && steps.filter.outputs.scratch-vm == 'true' }}
        uses: ./.github/actions/test-package
        with:
          package_name: scratch-vm
      - name: Test scratch-gui
        if: ${{ !cancelled() && steps.filter.outputs.scratch-gui == 'true' }}
        uses: ./.github/actions/test-package
        with:
          package_name: scratch-gui
