name: "Signature Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  signature-assistant:
    uses: scratchfoundation/scratch-agreements/.github/workflows/assistant.yml@main
    secrets:
      GHA_AGREEMENTS_PAT: ${{ secrets.GHA_AGREEMENTS_PAT }}
